# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- brew update
- brew outdated xctool || brew upgrade xctool
script:
- xcodebuild test -workspace Example/ChronosSwift.xcworkspace -scheme ChronosSwift-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' build-for-testing ONLY_ACTIVE_ARCH=NO
- xctool run-tests -workspace Example/ChronosSwift.xcworkspace -scheme ChronosSwift-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --allow-warnings
- pod spec lint --allow-warnings
- pod trunk push --allow-warnings
